// Keep the original cascade order. Edit source CSS, then run npm run build:css.
const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
const files=JSON.parse(fs.readFileSync(path.join(__dirname,'styles-manifest.json'),'utf8'));
const output='/* Generated by scripts/build-styles.cjs. Do not edit directly. */\n'+files.map(file=>'/* Source: '+file+' */\n'+fs.readFileSync(path.join(root,file),'utf8')+'\n').join('\n');
const target=path.join(root,'assets/styles.css');
if(process.argv.includes('--check')){
 if(!fs.existsSync(target)||fs.readFileSync(target,'utf8')!==output){console.error('CSS bundle is stale. Run npm run build:css.');process.exitCode=1;}
}else{fs.writeFileSync(target,output);console.log('Bundled '+files.length+' stylesheets in cascade order.');}
