import {test} from 'vitest';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(__dirname,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');

test('13.6 PWA is generated by vite-plugin-pwa from Vite hashed assets',()=>{
 const vite=read('vite.config.mjs'),pkg=JSON.parse(read('package.json')),sw=read('src/sw.js');
 assert.equal(pkg.devDependencies['vite-plugin-pwa'],'1.3.0');
 assert.match(vite,/VitePWA/);
 assert.match(vite,/strategies:'injectManifest'/);
 assert.match(vite,/srcDir:'src'/);
 assert.match(vite,/filename:'sw\.js'/);
 assert.match(vite,/globPatterns:\['\*\*\/\*\.\{js,css,html,svg,png,ico,webmanifest\}'\]/);
 assert.match(sw,/precacheAndRoute\(self\.__WB_MANIFEST/);
 assert.equal(fs.existsSync(path.join(root,'public/sw.js')),false,'static hand-maintained service worker must be removed');
 assert.equal(fs.existsSync(path.join(root,'src/sw.js')),true,'injectManifest worker source must live under src');
});

test('13.6 generated worker preserves offline navigation, same-origin precache and Web Push',()=>{
 const sw=read('src/sw.js');
 assert.match(sw,/matchPrecache\('\/index\.html'\)/);
 assert.doesNotMatch(sw,/cdn\.jsdelivr/);

 assert.match(sw,/addEventListener\('push'/);
 assert.match(sw,/showNotification/);
 assert.match(sw,/addEventListener\('notificationclick'/);
 assert.match(sw,/SKIP_WAITING/);
});

test('13.6 PWA update bridge never bypasses the durable cloud-save reload guard',()=>{
 const features=read('src/modules/features.js'),bridge=read('src/modules/pwa.js'),core=read('src/app.js'),main=read('src/main.js');
 assert.match(bridge,/virtual:pwa-register/);
 assert.match(bridge,/onNeedRefresh/);
 assert.match(features,/window\.ATPWA136\.register/);
 assert.match(features,/if\(ctx\.canReload&&!ctx\.canReload\(\)\)/);
 assert.match(features,/await pwaUpdater\(true\)/);
 assert.match(core,/canReload:\(\)=>!cloudSaving&&!\(cloudDirty&&cloudMirrorUnavailable\)/);
 assert.ok(main.indexOf('./modules/pwa.js')<main.indexOf('./modules/features.js'));
});
